{% set name = "crispy" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3330e808cfb536dfa85c47e61a32f39982e854c1086bea849adef38a0d132d5c

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python
  entry_points:
    - crispy = crispy.__main__:main

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
  run:
    - h5py
    - matplotlib-base
    - numpy
    - python >=2.7
    - silx-base

test:
  imports:
    - crispy
    - crispy.gui
    - crispy.gui.icons
    - crispy.gui.uis
    - crispy.modules
    - crispy.modules.orca
    - crispy.modules.quanty
    - crispy.utils

about:
  home: https://github.com/mretegan/crispy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Core-Level Spectroscopy Simulations in Python
  doc_url: http://www.esrf.eu/computing/scientific/crispy/
  dev_url: http://www.esrf.eu/computing/scientific/crispy/

extra:
  recipe-maintainers:
    - tschoonj
