travis:
  secure:
    BINSTAR_TOKEN: u0Y80Hk1zn3dedM+4tIzAnb8/A/moJH5AKxXFjDEp7LekVqNALVkCKkTt5GqbztNjOUgEOdISqiE6FvE5VYEWSnqpJCE5ycGM9rbzbQSSY3/PoMNl9+Fa6B/KujLFXS1lLL+Ro8Qtu1nP0k7BaZ4/wpcQj/3x46/RmbkFs7k65L0FatfprXicOdqfV7x2tZPDKkvvcV4ngmbpZV40asfbgZrAiZyDpB3zaMH/GhEIXqL/Js6jSj7L14VRvxsh6ZgmG4xhfSxXkGXuIKFqHvgeAOD6n+Gk8izbyGRB/nbCPLE9iZO4xk92MQW7pJicy8u6rRWn7KMxEbyQfsE7CAM6QMM2SbQa1kFuJRqGbtxxO2OfA6fieIKzt0SeNTKwPp204zwCxYyZWa1vlRNt85qETxDgxzb23qDOZPVbjoCSEfsf7nC7ShE7jDqQ2/nlGJoBpyhHS0dYWRM4WJjACftmUOZfh8Dvm5nUPrYO2XXqA69Q20ar6jJ/Dw/evhBXUHjuD+C2pHT7RrBO1oXLMJMVjLZGoKpmpSD/+JRXAcBmTVeHnNu/sEeDzmeSowfNtRaPRAvvs6HH1G5+7QmOu6fIYotY1+Y7xrQKOL6aUDyQpOYAZK7M9GDSggfQWBJzAGTNtOn9fmITAjXCrqGVQgFJ242fsaiYKcFfj1vg5nb090=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
